services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzSystems\EzPlatformAdminUi\UI\Module\Subitems\ValueObjectVisitor\SubitemsRow:
        parent: ezpublish_rest.output.value_object_visitor.base
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: EzSystems\EzPlatformAdminUi\UI\Module\Subitems\Values\SubitemsRow }

    EzSystems\EzPlatformAdminUi\UI\Module\Subitems\ValueObjectVisitor\SubitemsList:
        parent: ezpublish_rest.output.value_object_visitor.base
        autowire: true
        autoconfigure: false
        public: true
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: EzSystems\EzPlatformAdminUi\UI\Module\Subitems\Values\SubitemsList }

    EzSystems\EzPlatformAdminUi\UI\Module\Subitems\ContentViewParameterSupplier:
        $outputVisitor: '@ezplatform.adminui.rest.output.visitor.json'
        $outputGenerator: '@ezplatform.adminui.rest.output.generator.json'
        $contentTypeInfoListValueObjectVisitor: '@ezpublish_rest.output.value_object_visitor.ContentTypeInfoList'
